name: Portfolio Deployment

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu environment

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2  # Use v2 as it's the latest stable version

    # Step 2: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change this to the region of your S3 bucket

    # Step 3: Deploy static site to S3 bucket
    - name: Deploy static site to S3 bucket
      run: |
        aws s3 sync ./ s3://demo-portfolio-project --delete  # Sync the local directory to the S3 bucket
